version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=myPolicies
    ports:
      - '5432:5432'
